language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project manaticr/platformsh-drupal-template:8.x-dev test-site --stability dev --no-interaction
  - cd test-site
  - composer install
  - composer config repositories.manati_base_config path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
before_script:
  - cd ~/test-site
  - composer require manaticr/manati_base_config:"*"
script:
  - ./vendor/bin/drush si bloom -y --db-url=sqlite://tmp/.ht.sqlite
  - ./vendor/bin/drush en manati_base_config -y
  - ./vendor/bin/drush pmu manati_base_config -y
  - ./vendor/bin/drush cim -y --source=./modules/contrib/manati_base_config/config/partial --partial
