language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project drupal/recommended-project:^8.9 test-bloom --no-interaction
  - cd test-bloom
  - composer config repositories.chirripo path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
  - composer require manaticr/bloom:^1.0
  - composer require drush/drush
before_script:
  - cd ~/test-bloom
  - composer require manaticr/manati_base_config:"*"
script:
  - ./vendor/bin/drush si bloom -y --db-url=sqlite://tmp/.ht.sqlite
  - ./vendor/bin/drush en manati_base_config
  - ./vendor/bin/drush pmu manati_base_config
  - ./vendor/bin/drush cim --source=./modules/contrib/manati_base_config/config/partial --partial
