language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project drupal/recommended-project:^8.9 test-site --no-interaction
  - cd test-site
  - composer config repositories.manati_base_config path $TRAVIS_BUILD_DIR
  - composer config extra.enable-patching true
  - composer require drupal/admin_toolbar:^2.3 drupal/better_exposed_filters:^4.0 drupal/config_split:^1.4 drupal/devel:^4.0 drupal/environment_indicator:^4.0 drupal/focal_point:^1.5 drupal/image_style_quality:^1.4 drupal/media_entity_facebook:^2.0 drupal/media_entity_instagram:^3.0 drupal/media_entity_twitter:^2.4 drupal/metatag:^1.14 drupal/pathauto:^1.8 drupal/quicklink:^1.3 drupal/retina_images:1.x-dev drupal/seckit:^2.0 drupal/shs:^1.0 drupal/stage_file_proxy:^1.0 drupal/svg_image:^1.14 drupal/twig_tweak:^2.6 drupal/xmlsitemap:^1.0 drush/drush manaticr/bloom:8.x-dev
before_script:
  - cd ~/test-site
  - composer require manaticr/manati_base_config:"*"
script:
  - ./vendor/bin/drush si bloom -y --db-url=sqlite://tmp/.ht.sqlite
  - ./vendor/bin/drush en manati_base_config -y
  - ./vendor/bin/drush pmu manati_base_config -y
  - ./vendor/bin/drush cim -y --source=./modules/contrib/manati_base_config/config/partial --partial
